name: Release

# dot'n auto publish in npm
# on:
#   push:
#     branches:
#       - master

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Are you sure about that? the dev-template is not ready to be published!'
        type: boolean
        options:
          - Sim
        required: true


jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install dependencies and build
        run: |
          yarn
          yarn build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn release
